### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ghost** [ketanmistry/ihavecookies#1]
Hi I don't think that is GDPR, you have to do the following things:

1. Let users opt-in
2. Let users opt-out
3. Store the results in an encrypted method

etc.

**Comment by ketanmistry** [comment]
Hi @ayumihamsaki 

Thanks for your feedback.

This plugin is mainly for managing cookie and privacy policy consent and not for encrypting data etc. It's still very much a work in progress but I think it covers the basics for this:

1. Asking the user to accept cookies and what they are used for.
2. Getting approval of a privacy policy (which should contain details of where data is stored and how /what/where it is used for, etc).
3. Making sure that any checkboxes are not in a checked state on page load to ensure users must opt-in. This option is more targeted towards marketing preferences which are often checked by default (which they can no longer be).

At the moment, the plugin provides only a "Accept" button and there should really be a "Reject" button if they want to keep browsing the site but not have cookies set. One for me to add! 😄

**Comment by ghost** [comment]
Hi @ketanmistry Good luck with the plugin! Yes totally understand early days making it. I think there is one more thing, I believe you must give consent to each different type of cookie so for example:

Marketing cookies
Form cookies
etc.

Then let the users be able to select which ones they allow. GDPR is a headache in that regards.

**Comment by ketanmistry** [comment]
Yes, I thought that might be the case @ayumihamsaki. There seems to be a fair bit of confusion around to exactly what needs to be done for GDPR. Hopefully, this plugin will make it easier for everyone!

**Comment by ghost** [comment]
Yes, hope it will make this cookie GDPR issue much easier, will be watching this project - have high hopes for it. Looks good so far!
