### ISSUE TITLE
$('body').ihavecookies(); not working

### ISSUE THREAD

**Issue by Allmedialab** [ketanmistry/ihavecookies#11]
Hi,

Trying to initialize your script but $('body').ihavecookies(); returns a  "Uncaught TypeError: $(...).ihavecookies is not a function"

$.gdprcookie.init({ works!

Can you please create a working demo with $('body').ihavecookies(); and Google Analytics the most common cookies to stop before acceptance?

Regards & Thanks,
David

**Comment by PaulB007** [comment]
I am having the same problem ?

.ihavecookies is not a function

**Comment by Sharifur** [comment]
@Allmedialab  can you please share details how you solve this problem, i am facing same issue
