### ISSUE TITLE
How can i disable the third party scripts using ihavecookies

### ISSUE THREAD

**Issue by Reshmysandeep** [ketanmistry/ihavecookies#12]
Hi,

Please help me, how can I hide the third-party scripts and youtube iframe using ihavecookies.

**Comment by ketanmistry** [comment]
Hi @Reshmysandeep 

You can use the method `$.fn.ihavecookies.preference(cookieTypeValue)` for checking the value of cookies in js, so for example:

```
if ($.fn.ihavecookies.preference('analytics') == true) {
    // Run analytics code here (probably need to convert to a function first)...
}
```

For the youtube iframes, you may need to either convert the code to js and call it as a function or use PHP as an alternative to check the value of `cookieControlPrefs` and `cookieControl` cookies.

**Comment by Reshmysandeep** [comment]
@ketanmistry 

I have used this, But am always getting false for  $.fn.ihavecookies.preference('analytics')
