### ISSUE TITLE
Click events bind multiple times

### ISSUE THREAD

**Issue by onlysli** [ketanmistry/ihavecookies#15]
Click events for #gdpr-cookie-accept and #gdpr-cookie-advanced are binded each time the ihavecookies gets reinitialized (for example when user clicks a button to open again the settings).

I think it can be fixed adding something like this:
- before line #99: 
`$('body').off('click', '#gdpr-cookie-accept');`
- before line #119:
`$('body').off('click', '#gdpr-cookie-advanced');`

Thanks.

**Comment by steinhaug** [comment]
I came across this aswell, there is a quick fix for this. You can add the following:

Change 1 :
```javascript
$('body').on('click','#gdpr-cookie-accept', function(){
```
with:

```javascript
$('body').on('click','#gdpr-cookie-accept', function(e){
    e.preventDefault();
    e.stopPropagation();
    e.stopImmediatePropagation();
```

Change 2 :
```javascript
$('body').on('click', '#gdpr-cookie-advanced', function(){
```
with:

```javascript
$('body').on('click', '#gdpr-cookie-advanced', function(e){
    e.preventDefault();
    e.stopPropagation();
    e.stopImmediatePropagation();
```

This will prevent the event from bubbling / propagating so you only get 1 fired event, in the case of multiple re-initializations.

**Comment by ketanmistry** [comment]
@onlysli @steinhaug I've not come across this problem yet, but I will investigate! @steinhaug code is the best workaround for now. 👍
