### ISSUE TITLE
Keep cookie categories checked by default

### ISSUE THREAD

**Issue by ghost** [ketanmistry/ihavecookies#16]
First off, great script - simple and to the point. Spent the last little while getting it to work for me (and making all third party scripts into functions).

So one of the additions I've made is to auto accept the cookies after X seconds (a simple trigger of the Accept All Cookies button)

The problem I have is that, if within that time, someone clicks on Preferences, the only ticked option is of course the necessary cookies. If they now click "Accept Cookies", only the necessary cookies get saved.

Is there a way to make it so that all the cookie categories are ticked by default, when the Preferences / Advanced Settings button is clicked? 
That is of course if the user hasn't set cookie options previously (i.e. new user)

**Comment by jmsans** [comment]
You can replace this (line 123):

` $('input[name="gdpr[]"]:not(:disabled)').attr('data-auto', 'off').prop('checked', false);`

with this:

`$('input[name="gdpr[]"]:not(:disabled)').attr('data-auto', 'off').prop('checked', true);`
