### ISSUE TITLE
Cookie values have commas in, which breaks server-side parsing

### ISSUE THREAD

**Issue by MK-Chris** [ketanmistry/ihavecookies#17]
When cookies are accepted, if multiple cookie types are selected, the cookie value has a comma in.  As far as I know this breaks the standard?  Certainly the parse routine I'm using on the server (Perl's CGI::Simple::Cookie->parse()) splits on commas and semi-colons, so the cookie set by this plugin breaks it.

I can't see anyway of setting a custom cookie type separator, but perhaps this would be the best way round that?

**Comment by MK-Chris** [comment]
Have created a pull request to fix this (#18).

**Comment by ketanmistry** [comment]
Thanks @MK-Chris, I’ve commented on your pull request.
