### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by farmwork99** [ketanmistry/ihavecookies#4]
Do you plan to provide a localization? This would be perfect for multilingual websites. 
Anyway - thanks a lot for your excellent work!

**Comment by ketanmistry** [comment]
@farmwork99 I didn't, but that's a great idea! 😃 

I'm not sure where I'd start with it though? Any suggestions are more than welcome.

**Comment by bre7** [comment]
Possible solution: Retrieve the locale from the browser and check for the appropriate text translations.

E.g.

The plugin should only include localization-en to avoid bloating. (Example was translated using deepl)

```js
$('body').ihavecookies({
    
    // Text (default & translations)
    localization: {
        en: {
            // A custom title for the popup
            title: "Cookies & Privacy",

            // Add your own cookie message here, if you prefer not to use the
            // default one. HTML can be included within this message.
            message: "Cookies enable you to use shopping carts ..."
        },
        de: {
            // A custom title for the popup
            title: "Cookies & Datenschutz",

            // Add your own cookie message here, if you prefer not to use the
            // default one. HTML can be included within this message.
            message: "Cookies ermöglichen es Ihnen, Warenkörbe zu verwenden ..."
        },
    }
    
});
```

**Comment by farmwork99** [comment]
@bre7 
I apologize for my very late feedback. But with the new privacy policy in europe, in the last few weeks, I've done nothing but make customer websites compliant.

Your solution seems simple and good - I will definitely try it.
Many thanks for your effort and best wishes from Germany
...Michael
