### ISSUE TITLE
Hardcoded options

### ISSUE THREAD

**Issue by molnargabor** [ketanmistry/ihavecookies#6]
Hello!

I would like to customize the texts but unfortunatelly 2 of them are hardcoded.
Could you please put these two labels into options?
1. H5 tag: "Select cookies to accept"
2. The first cookie type checkbox label: "Necessary"

These are important if you make non-english sites.

Thank you so much!

**Comment by ketanmistry** [comment]
Hey @molnargabor, I've added those options in now - readme has been updated accordingly. 😄
